add_newline = false

format = "$directory $git_branch$git_status$cmd_duration$character"

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "
style = "bold purple"
format = "[$symbol$branch]($style) "

[git_status]
style = "red"
format = "([✗$modified$staged$untracked$ahead_behind]($style)) "
modified = ""
staged = ""
untracked = ""
ahead = "↑"
behind = "↓"
diverged = "↕"
up_to_date = ""
conflicted = "!"

[cmd_duration]
min_time = 800
style = "yellow"
format = "[$duration]($style) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
